[2022-11-04 12:12:13,369] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.t1 scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-11-04 12:12:13,384] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xcom_dag.t1 scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-11-04 12:12:13,385] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-04 12:12:13,387] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-04 12:12:13,388] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-04 12:12:13,406] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): t1> on 2022-11-03 00:00:00+00:00
[2022-11-04 12:12:13,422] {standard_task_runner.py:52} INFO - Started process 2134 to run task
[2022-11-04 12:12:13,427] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xcom_dag', 't1', 'scheduled__2022-11-03T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/xcom_dag.py', '--cfg-path', '/tmp/tmpybgpigk4', '--error-file', '/tmp/tmppiup4uqd']
[2022-11-04 12:12:13,428] {standard_task_runner.py:80} INFO - Job 38: Subtask t1
[2022-11-04 12:12:13,483] {task_command.py:369} INFO - Running <TaskInstance: xcom_dag.t1 scheduled__2022-11-03T00:00:00+00:00 [running]> on host 0636e12a55b7
[2022-11-04 12:12:13,547] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xcom_dag
AIRFLOW_CTX_TASK_ID=t1
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T00:00:00+00:00
[2022-11-04 12:12:13,568] {python.py:173} INFO - Done. Returned value was: None
[2022-11-04 12:12:13,580] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=xcom_dag, task_id=t1, execution_date=20221103T000000, start_date=20221104T121213, end_date=20221104T121213
[2022-11-04 12:12:13,608] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-04 12:12:13,685] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
