[2022-10-31 19:14:37,616] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-10-30T00:00:00+00:00 [queued]>
[2022-10-31 19:14:37,628] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-10-30T00:00:00+00:00 [queued]>
[2022-10-31 19:14:37,629] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 19:14:37,630] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-10-31 19:14:37,631] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 19:14:37,646] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-10-30 00:00:00+00:00
[2022-10-31 19:14:37,652] {standard_task_runner.py:52} INFO - Started process 13124 to run task
[2022-10-31 19:14:37,660] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-10-30T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp5fl1f2u2', '--error-file', '/tmp/tmp878wmtg5']
[2022-10-31 19:14:37,663] {standard_task_runner.py:80} INFO - Job 11: Subtask is_api_available
[2022-10-31 19:14:37,948] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-10-30T00:00:00+00:00 [running]> on host 601dc51f5629
[2022-10-31 19:14:38,202] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-10-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-30T00:00:00+00:00
[2022-10-31 19:14:38,205] {http.py:97} INFO - Poking: api/
[2022-10-31 19:14:38,260] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-10-31 19:14:38,281] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-10-31 19:14:38,951] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-31 19:14:38,974] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20221030T000000, start_date=20221031T191437, end_date=20221031T191438
[2022-10-31 19:14:39,030] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-31 19:14:39,057] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
