[2022-11-03 18:16:32,413] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-03 18:16:32,423] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-03 18:16:32,426] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-03 18:16:32,427] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-03 18:16:32,429] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-03 18:16:32,442] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-11-02 00:00:00+00:00
[2022-11-03 18:16:32,453] {standard_task_runner.py:52} INFO - Started process 68969 to run task
[2022-11-03 18:16:32,461] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpfitz9xj7', '--error-file', '/tmp/tmpl1kxazva']
[2022-11-03 18:16:32,463] {standard_task_runner.py:80} INFO - Job 14: Subtask is_api_available
[2022-11-03 18:16:32,568] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-11-02T00:00:00+00:00 [running]> on host 601dc51f5629
[2022-11-03 18:16:32,667] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2022-11-03 18:16:32,671] {http.py:97} INFO - Poking: api/
[2022-11-03 18:16:32,720] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-11-03 18:16:32,737] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-11-03 18:16:33,498] {base.py:301} INFO - Success criteria met. Exiting.
[2022-11-03 18:16:33,516] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20221102T000000, start_date=20221103T181632, end_date=20221103T181633
[2022-11-03 18:16:33,570] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-03 18:16:33,618] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
