[2022-11-04 00:15:40,291] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-11-04 00:15:40,323] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-03T00:00:00+00:00 [queued]>
[2022-11-04 00:15:40,326] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-04 00:15:40,330] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-04 00:15:40,334] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-04 00:15:40,394] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-03 00:00:00+00:00
[2022-11-04 00:15:40,411] {standard_task_runner.py:52} INFO - Started process 71558 to run task
[2022-11-04 00:15:40,423] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-11-03T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp7ijti75l', '--error-file', '/tmp/tmpzxg7ltcd']
[2022-11-04 00:15:40,433] {standard_task_runner.py:80} INFO - Job 18: Subtask create_table
[2022-11-04 00:15:40,553] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-11-03T00:00:00+00:00 [running]> on host 601dc51f5629
[2022-11-04 00:15:40,668] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T00:00:00+00:00
[2022-11-04 00:15:40,689] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-11-04 00:15:40,697] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-11-04 00:15:40,700] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-11-04 00:15:40,719] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221103T000000, start_date=20221104T001540, end_date=20221104T001540
[2022-11-04 00:15:40,768] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-04 00:15:40,837] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
