[2022-11-03 18:16:37,565] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.process_user scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-03 18:16:37,581] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.process_user scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-03 18:16:37,582] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-03 18:16:37,583] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-03 18:16:37,584] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-03 18:16:37,613] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): process_user> on 2022-11-02 00:00:00+00:00
[2022-11-03 18:16:37,648] {standard_task_runner.py:52} INFO - Started process 68985 to run task
[2022-11-03 18:16:37,659] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'process_user', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpdjtl1og4', '--error-file', '/tmp/tmp_x39y2ek']
[2022-11-03 18:16:37,663] {standard_task_runner.py:80} INFO - Job 16: Subtask process_user
[2022-11-03 18:16:37,834] {task_command.py:369} INFO - Running <TaskInstance: user_processing.process_user scheduled__2022-11-02T00:00:00+00:00 [running]> on host 601dc51f5629
[2022-11-03 18:16:37,889] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=process_user
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2022-11-03 18:16:37,959] {python.py:173} INFO - Done. Returned value was: None
[2022-11-03 18:16:37,975] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=process_user, execution_date=20221102T000000, start_date=20221103T181637, end_date=20221103T181637
[2022-11-03 18:16:38,040] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-03 18:16:38,067] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
