[2022-11-03 18:16:30,580] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-03 18:16:30,605] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-11-02T00:00:00+00:00 [queued]>
[2022-11-03 18:16:30,607] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-03 18:16:30,608] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-03 18:16:30,614] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-03 18:16:30,648] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-11-02 00:00:00+00:00
[2022-11-03 18:16:30,677] {standard_task_runner.py:52} INFO - Started process 68966 to run task
[2022-11-03 18:16:30,688] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-11-02T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp71nq3af_', '--error-file', '/tmp/tmpqek3dd0q']
[2022-11-03 18:16:30,694] {standard_task_runner.py:80} INFO - Job 13: Subtask create_table
[2022-11-03 18:16:30,893] {task_command.py:369} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-11-02T00:00:00+00:00 [running]> on host 601dc51f5629
[2022-11-03 18:16:31,044] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-02T00:00:00+00:00
[2022-11-03 18:16:31,064] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-11-03 18:16:31,086] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-11-03 18:16:31,090] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-11-03 18:16:31,114] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221102T000000, start_date=20221103T181630, end_date=20221103T181631
[2022-11-03 18:16:31,194] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-03 18:16:31,248] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
