[2022-11-04 11:37:26,555] {processor.py:153} INFO - Started process (PID=862) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:37:26,557] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:37:26,559] {logging_mixin.py:115} INFO - [2022-11-04 11:37:26,559] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:37:26,575] {logging_mixin.py:115} INFO - [2022-11-04 11:37:26,572] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:37:26,577] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:37:26,603] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.053 seconds
[2022-11-04 11:37:57,495] {processor.py:153} INFO - Started process (PID=893) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:37:57,498] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:37:57,501] {logging_mixin.py:115} INFO - [2022-11-04 11:37:57,501] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:37:57,527] {logging_mixin.py:115} INFO - [2022-11-04 11:37:57,519] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:37:57,532] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:37:57,589] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.101 seconds
[2022-11-04 11:38:27,864] {processor.py:153} INFO - Started process (PID=924) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:38:27,867] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:38:27,870] {logging_mixin.py:115} INFO - [2022-11-04 11:38:27,870] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:38:27,881] {logging_mixin.py:115} INFO - [2022-11-04 11:38:27,880] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:38:27,883] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:38:27,905] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.046 seconds
[2022-11-04 11:38:58,677] {processor.py:153} INFO - Started process (PID=947) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:38:58,681] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:38:58,683] {logging_mixin.py:115} INFO - [2022-11-04 11:38:58,683] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:38:58,702] {logging_mixin.py:115} INFO - [2022-11-04 11:38:58,700] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:38:58,704] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:38:58,745] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.090 seconds
[2022-11-04 11:39:28,901] {processor.py:153} INFO - Started process (PID=978) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:39:28,922] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:39:28,925] {logging_mixin.py:115} INFO - [2022-11-04 11:39:28,925] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:39:28,944] {logging_mixin.py:115} INFO - [2022-11-04 11:39:28,939] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:39:28,954] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:39:28,982] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.097 seconds
[2022-11-04 11:39:59,779] {processor.py:153} INFO - Started process (PID=1009) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:39:59,785] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:39:59,790] {logging_mixin.py:115} INFO - [2022-11-04 11:39:59,789] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:39:59,826] {logging_mixin.py:115} INFO - [2022-11-04 11:39:59,825] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:39:59,846] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:40:00,000] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.248 seconds
[2022-11-04 11:40:30,250] {processor.py:153} INFO - Started process (PID=1031) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:40:30,253] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:40:30,266] {logging_mixin.py:115} INFO - [2022-11-04 11:40:30,266] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:40:30,311] {logging_mixin.py:115} INFO - [2022-11-04 11:40:30,306] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:40:30,318] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:40:30,357] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.113 seconds
[2022-11-04 11:41:01,161] {processor.py:153} INFO - Started process (PID=1062) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:41:01,165] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:41:01,168] {logging_mixin.py:115} INFO - [2022-11-04 11:41:01,168] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:41:01,231] {logging_mixin.py:115} INFO - [2022-11-04 11:41:01,230] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:41:01,239] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:41:01,362] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.224 seconds
[2022-11-04 11:41:31,591] {processor.py:153} INFO - Started process (PID=1095) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:41:31,594] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:41:31,596] {logging_mixin.py:115} INFO - [2022-11-04 11:41:31,596] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:41:31,635] {logging_mixin.py:115} INFO - [2022-11-04 11:41:31,631] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:41:31,637] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:41:31,674] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.088 seconds
[2022-11-04 11:42:01,897] {processor.py:153} INFO - Started process (PID=1118) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:42:01,901] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:42:01,906] {logging_mixin.py:115} INFO - [2022-11-04 11:42:01,905] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:42:01,927] {logging_mixin.py:115} INFO - [2022-11-04 11:42:01,924] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:42:01,932] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:42:02,007] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.139 seconds
[2022-11-04 11:42:32,704] {processor.py:153} INFO - Started process (PID=1152) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:42:32,706] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:42:32,707] {logging_mixin.py:115} INFO - [2022-11-04 11:42:32,707] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:42:32,717] {logging_mixin.py:115} INFO - [2022-11-04 11:42:32,716] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:42:32,720] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:42:32,759] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.059 seconds
[2022-11-04 11:43:03,364] {processor.py:153} INFO - Started process (PID=1185) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:43:03,372] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:43:03,409] {logging_mixin.py:115} INFO - [2022-11-04 11:43:03,409] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:43:03,478] {logging_mixin.py:115} INFO - [2022-11-04 11:43:03,474] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:43:03,483] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:43:03,596] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.283 seconds
[2022-11-04 11:43:34,133] {processor.py:153} INFO - Started process (PID=1213) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:43:34,135] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:43:34,136] {logging_mixin.py:115} INFO - [2022-11-04 11:43:34,136] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:43:34,148] {logging_mixin.py:115} INFO - [2022-11-04 11:43:34,147] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:43:34,150] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:43:34,174] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.044 seconds
[2022-11-04 11:44:04,406] {processor.py:153} INFO - Started process (PID=1248) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:44:04,416] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:44:04,453] {logging_mixin.py:115} INFO - [2022-11-04 11:44:04,453] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:44:04,602] {logging_mixin.py:115} INFO - [2022-11-04 11:44:04,577] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:44:04,670] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:44:04,792] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.393 seconds
[2022-11-04 11:44:35,215] {processor.py:153} INFO - Started process (PID=1273) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:44:35,217] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:44:35,218] {logging_mixin.py:115} INFO - [2022-11-04 11:44:35,218] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:44:35,228] {logging_mixin.py:115} INFO - [2022-11-04 11:44:35,227] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:44:35,230] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:44:35,263] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.053 seconds
[2022-11-04 11:45:05,896] {processor.py:153} INFO - Started process (PID=1305) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:45:05,898] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:45:05,899] {logging_mixin.py:115} INFO - [2022-11-04 11:45:05,899] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:45:05,908] {logging_mixin.py:115} INFO - [2022-11-04 11:45:05,908] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:45:05,910] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:45:05,930] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.036 seconds
[2022-11-04 11:45:36,787] {processor.py:153} INFO - Started process (PID=1340) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:45:36,791] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:45:36,794] {logging_mixin.py:115} INFO - [2022-11-04 11:45:36,794] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:45:36,812] {logging_mixin.py:115} INFO - [2022-11-04 11:45:36,808] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:45:36,814] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:45:36,864] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.082 seconds
[2022-11-04 11:46:07,091] {processor.py:153} INFO - Started process (PID=1364) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:46:07,093] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:46:07,095] {logging_mixin.py:115} INFO - [2022-11-04 11:46:07,095] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:46:07,105] {logging_mixin.py:115} INFO - [2022-11-04 11:46:07,104] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:46:07,107] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:46:07,161] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.075 seconds
[2022-11-04 11:46:37,464] {processor.py:153} INFO - Started process (PID=1399) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:46:37,465] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:46:37,467] {logging_mixin.py:115} INFO - [2022-11-04 11:46:37,467] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:46:37,479] {logging_mixin.py:115} INFO - [2022-11-04 11:46:37,477] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:46:37,485] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:46:37,548] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.090 seconds
[2022-11-04 11:47:08,070] {processor.py:153} INFO - Started process (PID=1433) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:47:08,080] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:47:08,083] {logging_mixin.py:115} INFO - [2022-11-04 11:47:08,083] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:47:08,090] {logging_mixin.py:115} INFO - [2022-11-04 11:47:08,089] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:47:08,091] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:47:08,117] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.050 seconds
[2022-11-04 11:47:38,723] {processor.py:153} INFO - Started process (PID=1456) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:47:38,730] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:47:38,732] {logging_mixin.py:115} INFO - [2022-11-04 11:47:38,732] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:47:38,743] {logging_mixin.py:115} INFO - [2022-11-04 11:47:38,742] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:47:38,745] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:47:38,773] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.053 seconds
[2022-11-04 11:48:09,535] {processor.py:153} INFO - Started process (PID=1489) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:48:09,538] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:48:09,542] {logging_mixin.py:115} INFO - [2022-11-04 11:48:09,542] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:48:09,558] {logging_mixin.py:115} INFO - [2022-11-04 11:48:09,555] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:48:09,563] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:48:09,640] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.110 seconds
[2022-11-04 11:48:39,757] {processor.py:153} INFO - Started process (PID=1519) to work on /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:48:39,761] {processor.py:641} INFO - Processing file /opt/airflow/dags/subdags/subdag_downloads.py for tasks to queue
[2022-11-04 11:48:39,763] {logging_mixin.py:115} INFO - [2022-11-04 11:48:39,763] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:48:39,780] {logging_mixin.py:115} INFO - [2022-11-04 11:48:39,778] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/subdags/subdag_downloads.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 5
    with DAG(f"{parent_dag_id}.{child_dag_id")
                                             ^
SyntaxError: invalid syntax
[2022-11-04 11:48:39,782] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/subdags/subdag_downloads.py
[2022-11-04 11:48:39,817] {processor.py:161} INFO - Processing /opt/airflow/dags/subdags/subdag_downloads.py took 0.066 seconds
